echo "|******************** Welcome Message  💌 ********************|"
echo "+                                                             +"
echo "|             Welcome in DataBase Managment System            |"
echo "+  Here we design our system to make everything Easy for you  +"
echo "|                       Hope You enjoy!                       |"
echo "+                                                             +"
echo "***************************************************************"
echo "                                                               "
echo "----------------------- Let's Start 😉 ------------------------"
echo "                                                               "
echo "                                                               "
echo " ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️"
echo " ⚠️   You Must take care about TWO things         ⚠️ "
echo " ⚠️   [1] DataBase System is Case Sensetive.      ⚠️ "
echo " ⚠️   [2] Pick a Real Number when you asked for.  ⚠️ "
echo " ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️"
echo "                                                               "
echo "                                                               "
./Menu.sh 